theme: jekyll-theme-minimal
#title: boring technology
description: technology is boring if it has been proven to work reliably and has user adoption that is able to sustain a community around it. this site is an opionated list of boring technologies.
